export enum FieldTypes {
  AutoComplete = 'autocomplete',
  Button = 'button',
  CheckBox = 'checkbox',
  DataGrid = 'datagrid',
  DatePicker = 'date',
  DateCombo = 'date',
  ComboBox = 'dropdown',
  DropDown = 'dropdown',
  File = 'file',
  Input = 'text',
  Text = 'text',
  Email = 'email',
  Number = 'number',
  Password = 'password',
  Radio = 'radio',
  Currency = 'currency',
  Unit = 'unit',
  Id = 'id'
}
